{
  "language": "shell",
  "os": [
    "osx",
    "linux"
  ],
  "jobs": {
    "include": [
      {
        "stage": "iOS_Test",
        "os": "osx",
        "osx_image": "xcode11",
        "git": {
          "depth": 3
        },
        "before_script": [
          "open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app",
          "brew update",
          "brew install libimobiledevice",
          "brew install ideviceinstaller",
          "brew install ios-deploy",
          "sudo gem install cocoapods",
          "git clone https://github.com/flutter/flutter.git -b beta",
          "export PATH=\"$PATH\":\"$HOME/.pub-cache/bin\"",
          "export PATH=`pwd`/flutter/bin:`pwd`/flutter/bin/cache/dart-sdk/bin:$PATH",
          "flutter precache",
          "flutter doctor -v",
          "flutter devices",
          "flutter packages get",
          "flutter packages pub run build_runner build --delete-conflicting-outputs",
          "cd example"
        ],
        "script": [
          "./test_driver/run_tests.sh iPhone X"
        ],
        "cache": {
          "directories": [
            "$HOME/.pub-cache"
          ]
        },
        "branches": {
          "only": [
            "bodnar/19570/tests"
          ]
        }
      }
    ]
  }
}