name: backendless_sdk
description: Flutter plugin for Backendless SDK. It provides access to the Backendless services that enable the server-side functionality for developing and running mobile and desktop apps.
version: 8.0.0-alpha.12
homepage: https://backendless.com

environment:
  sdk: ">=2.17.5 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  reflectable: ^4.0.2
  connectivity_plus: ^2.0.2
  device_info_plus: ^8.0.0
  socket_io_client: ^1.0.2
  uuid: ^3.0.6
  synchronized: ^3.0.0+2
  flutter_secure_storage: ^7.0.1
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.2
  flutter_local_notifications: ^13.0.0
  collection: ^1.16.0
  shared_preferences: ^2.1.2

  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.backendless.backendless_sdk
        pluginClass: BackendlessSdkPlugin
      ios:
        pluginClass: BackendlessSdkPlugin
      web:
        pluginClass: BackendlessSdkWeb
        fileName: backendless_sdk_web.dart

false_secrets:
  - /example/android/app/google-services.json
  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
example/android/app/google-services:
  json:
