name: backendless_sdk
description: Flutter plugin for Backendless SDK. It provides access to the Backendless services that enable the server-side functionality for developing and running mobile and desktop apps.
version: 6.0.1
homepage: https://backendless.com

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.14.11
  reflectable: ^2.2.1
  http: ^0.12.1
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  flutter_driver:
    sdk: flutter
  test: any
  path: any
  path_provider:
  intl:

flutter:
  plugin:
    platforms:
      android:
        package: com.backendless.backendless_sdk
        pluginClass: BackendlessSdkPlugin
      ios:
        pluginClass: BackendlessSdkPlugin
      web:
        pluginClass: BackendlessWeb
        fileName: backendless_sdk_web.dart