name: backendless_sdk
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  flutter_secure_storage : ^5.0.2
  reflectable: ^3.0.4
  build_runner: ^2.1.7
  firebase_messaging: ^11.2.6
  device_info: ^2.0.3
  firebase_core : ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter