// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import "dart:core";
import 'bus.dart' as prefix1;
import 'car.dart' as prefix2;
import 'package:backendless_sdk/backendless_sdk.dart' as prefix0;

// ignore:unused_import
import "package:reflectable/mirrors.dart" as m;
// ignore:unused_import
import "package:reflectable/src/reflectable_builder_based.dart" as r;
// ignore:unused_import
import "package:reflectable/reflectable.dart" as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): new r.ReflectorData(
      <m.TypeMirror>[
        new r.NonGenericClassMirrorImpl(
            r"Bus",
            r".Bus",
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 2, 11, 18],
            const <int>[19, 11, 20, 21, 22, 12, 13, 14, 15, 16, 17],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix1.Bus() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null),
        new r.NonGenericClassMirrorImpl(
            r"Car",
            r".Car",
            7,
            1,
            const prefix0.Reflector(),
            const <int>[3, 4, 5, 6, 7, 8, 9, 10, 23, 40],
            const <int>[
              19,
              23,
              20,
              21,
              22,
              24,
              25,
              26,
              27,
              28,
              29,
              30,
              31,
              32,
              33,
              34,
              35,
              36,
              37,
              38,
              39
            ],
            const <int>[],
            -1,
            {},
            {},
            {r"": (b) => () => b ? new prefix2.Car() : null},
            -1,
            -1,
            const <int>[-1],
            null,
            null)
      ],
      <m.DeclarationMirror>[
        new r.VariableMirrorImpl(
            r"s", 32773, 0, const prefix0.Reflector(), -1, -1, -1, null, null),
        new r.VariableMirrorImpl(
            r"i", 32773, 0, const prefix0.Reflector(), -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"dateTime", 32773, 0,
            const prefix0.Reflector(), -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"brand", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"model", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"price", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"year", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"isUsed", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"date", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"user", 32773, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.VariableMirrorImpl(r"bus", 2129925, 1, const prefix0.Reflector(),
            -1, -1, -1, null, null),
        new r.MethodMirrorImpl(r"toString", 131074, 0, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 0, -1, -1, 12),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 0, -1, -1, 13),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 1, -1, -1, 14),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 1, -1, -1, 15),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 2, -1, -1, 16),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 2, -1, -1, 17),
        new r.MethodMirrorImpl(r"", 64, 0, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"==", 131074, null, -1, -1, -1, null,
            const <int>[3], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"noSuchMethod", 65538, null, null, -1, -1, null,
            const <int>[4], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"hashCode", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"runtimeType", 131075, null, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.MethodMirrorImpl(r"toString", 131074, 1, -1, -1, -1, null,
            const <int>[], const prefix0.Reflector(), null),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 3, -1, -1, 24),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 3, -1, -1, 25),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 4, -1, -1, 26),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 4, -1, -1, 27),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 5, -1, -1, 28),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 5, -1, -1, 29),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 6, -1, -1, 30),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 6, -1, -1, 31),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 7, -1, -1, 32),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 7, -1, -1, 33),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 8, -1, -1, 34),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 8, -1, -1, 35),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 9, -1, -1, 36),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 9, -1, -1, 37),
        new r.ImplicitGetterMirrorImpl(
            const prefix0.Reflector(), 10, -1, -1, 38),
        new r.ImplicitSetterMirrorImpl(
            const prefix0.Reflector(), 10, -1, -1, 39),
        new r.MethodMirrorImpl(r"", 64, 1, -1, -1, -1, null, const <int>[],
            const prefix0.Reflector(), null)
      ],
      <m.ParameterMirror>[
        new r.ParameterMirrorImpl(r"_s", 32870, 13, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_i", 32870, 15, const prefix0.Reflector(),
            -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_dateTime", 32870, 17,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"other", 16390, 19,
            const prefix0.Reflector(), null, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"invocation", 32774, 20,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_brand", 32870, 25,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_model", 32870, 27,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_price", 32870, 29,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_year", 32870, 31,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_isUsed", 32870, 33,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_date", 32870, 35,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_user", 32870, 37,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null),
        new r.ParameterMirrorImpl(r"_bus", 2130022, 39,
            const prefix0.Reflector(), -1, -1, -1, null, null, null, null)
      ],
      <Type>[prefix1.Bus, prefix2.Car],
      2,
      {
        r"==": (dynamic instance) => (x) => instance == x,
        r"toString": (dynamic instance) => instance.toString,
        r"noSuchMethod": (dynamic instance) => instance.noSuchMethod,
        r"hashCode": (dynamic instance) => instance.hashCode,
        r"runtimeType": (dynamic instance) => instance.runtimeType,
        r"s": (dynamic instance) => instance.s,
        r"i": (dynamic instance) => instance.i,
        r"dateTime": (dynamic instance) => instance.dateTime,
        r"brand": (dynamic instance) => instance.brand,
        r"model": (dynamic instance) => instance.model,
        r"price": (dynamic instance) => instance.price,
        r"year": (dynamic instance) => instance.year,
        r"isUsed": (dynamic instance) => instance.isUsed,
        r"date": (dynamic instance) => instance.date,
        r"user": (dynamic instance) => instance.user,
        r"bus": (dynamic instance) => instance.bus
      },
      {
        r"s=": (dynamic instance, value) => instance.s = value,
        r"i=": (dynamic instance, value) => instance.i = value,
        r"dateTime=": (dynamic instance, value) => instance.dateTime = value,
        r"brand=": (dynamic instance, value) => instance.brand = value,
        r"model=": (dynamic instance, value) => instance.model = value,
        r"price=": (dynamic instance, value) => instance.price = value,
        r"year=": (dynamic instance, value) => instance.year = value,
        r"isUsed=": (dynamic instance, value) => instance.isUsed = value,
        r"date=": (dynamic instance, value) => instance.date = value,
        r"user=": (dynamic instance, value) => instance.user = value,
        r"bus=": (dynamic instance, value) => instance.bus = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
